### ISSUE TITLE
dragClass doesn't reflect css cursor attribute

### ISSUE THREAD

**Issue by socialmedialabs** [kutlugsahin/ngx-smooth-dnd#11]
Following your examples I tried adding a grabbing cursor to the ghost item, but with no luck:

```
.card-ghost {
	transition: transform 0.5s ease;
	transform: rotateZ(5deg);
	opacity: 0.75;
	cursor: -webkit-grabbing;
	cursor: grabbing;
}
```

Any idea how that can be achieved?

**Comment by kutlugsahin** [comment]
Hi @socialmedialabs thanks for submitting the issue. It should be fixed in version 0.2.3. Cheers!
