### ISSUE TITLE
The demo behave different when copied

### ISSUE THREAD

**Issue by fatnjazzy** [kutlugsahin/ngx-smooth-dnd#13]
Hi,
I have setup a project here: https://stackblitz.com/edit/angular-e2r3b7?file=src%2Fapp%2Fapp.component.ts

For some reason, when I drag around the cards, it is not placed where I dropped it, it goes to the bottom of the card list , can you tell whats wrong?

Thanks

**Comment by kutlugsahin** [comment]
Hey @fatnjazzy ,
There was an issue with v 0.2.0 which is fixed 0.2.1. the new version is also deployed to the demo page.
Please use ngx-smooth-dnd v0.2.1. Cheers!

**Comment by fatnjazzy** [comment]
Thanks. working.
