### ISSUE TITLE
Not correct in BoostrapModal

### ISSUE THREAD

**Issue by nchizhov** [kutlugsahin/ngx-smooth-dnd#25]
If we try to use this module inside boostrap modal - draggable not positioning in correct place when we drag it.

Example:
![image](https://user-images.githubusercontent.com/4849753/50290746-55e0ee80-0475-11e9-9c3d-b3660eda653e.png)

**Comment by joevchs** [comment]
Did you find a solution for this? 

The same is happening to me, ill appreciate your help.

**Comment by kutlugsahin** [comment]
See [getGhostParent](https://github.com/kutlugsahin/ngx-smooth-dnd#getghostparent)
