### ISSUE TITLE
Doesn't seem to work in IE11

### ISSUE THREAD

**Issue by jatin2505** [kutlugsahin/ngx-smooth-dnd#3]
SCRIPT5022: Exception thrown and not caught
File: polyfills.bundle.js, Line: 804, Column: 36

**Comment by kutlugsahin** [comment]
Some polyfills seem to be missing for the demo app. I will try to fix it soon. But library itself should work though.

**Comment by jatin2505** [comment]
I am getting this couple of errors multiple time (only on IE11) and not able to drag. I have not set any drag or drop class, and they are from smooth-dnd component (Angular)

**ERROR** TypeError: Unable to set property 'className' of undefined or null reference
   "ERROR"
   {
      [functions]: ,
      __proto__: { },
      description: "Unable to set property 'className' of undefined or null reference",
      message: "Unable to set property 'className' of undefined or null reference",
      name: "TypeError",
      ngDebugContext: { },
      number: -2146823281,
      stack: "TypeError: Unable to set property 'className' of undefined or null reference
   at DraggableComponent.prototype.ngAfterViewInit (eval code:20:9)
   at callProviderLifecycles (eval code:12964:9)
   at callElementProvidersLifecycles (eval code:12931:13)
   at callLifecycleHooksChildrenFirst (eval code:12914:17)
   at checkAndUpdateView (eval code:14069:5)
   at callViewAction (eval code:14411:21)
   at execEmbeddedViewsAction (eval code:14369:17)
   at checkAndUpdateView (eval code:14061:5)
   at callViewAction (eval code:14411:21)
   at execComponentViewsAction (eval code:14343:13)"
   }

**ERROR** CONTEXT [object Object]
   "ERROR CONTEXT"
   {
      [functions]: ,
      __proto__: { },
      component: { },
      componentRenderElement: { },
      context: { },
      elDef: { },
      elOrCompView: { },
      elView: { },
      injector: { },
      nodeDef: { },
      nodeIndex: 1,
      providerTokens: [ ],
      references: { },
      renderNode: { },
      view: { }
   }

Any ideas?

**Comment by kutlugsahin** [comment]
Yes you were right. Somehow parentElement of a viewchild was undefined in draggableComponent in ngAfterViewInit. It worked when when I used parentNode. fixed in v 0.1.6.

**Comment by jatin2505** [comment]
Hi kutlugsahin,
Something wrong in v0.1.6 and I can't drop the card now.
I took an angular 2 seed and added the CardsComponent. Here are the steps:
1) Cloned https://github.com/angular/angular2-seed
2) npm install
3) npm i ngx-smooth-dnd
4) Added the following cards code in a view
https://github.com/kutlugsahin/ngx-smooth-dnd/blob/master/apps/demo/src/pages/cards.ts

Request you to try and let me know if I am doing anything wrong.

**Comment by kutlugsahin** [comment]
just published a fix for it. try 0.1.7

**Comment by jatin2505** [comment]
Thanks so much, it works fine in Chrome and no errors in IE 11 as well.

I am trying to use this in a project but it breaks my build. Can you also look at the following error:

[!] Error: 'constants' is not exported by node_modules/ngx-smooth-dnd/node_modules/smooth-dnd/dist/index.js
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
node_modules/ngx-smooth-dnd/esm5/ngx-smooth-dnd.js (2:20)
1: import { Component, ViewChild, ContentChildren, Input, Output, EventEmitter, NgZone, NgModule } from '@angular/core';
2: import SmoothDnD, { constants, dropHandlers } from 'smooth-dnd';
                                          ^
3: import { CommonModule } from '@angular/common';
4: var DraggableComponent =               (function () {
