### ISSUE TITLE
ngx smooth dnd

### ISSUE THREAD

**Issue by Tanujasingh** [kutlugsahin/ngx-smooth-dnd#31]
Hi,
Is it working for Angularjs. I am pretty new for angular and want use drag and drop functionality in my project.
If it is working. Can you tell me how can i use it?  

Thanks and Regards
Tanuja

**Comment by kutlugsahin** [comment]
Hi @Tanujasingh 

The latest codebase supports angular 7.0. You can check the source of the demo pages top right code link [demo](https://kutlugsahin.github.io/ngx-smooth-dnd/)

Cheers!
