### ISSUE TITLE
update to Angular v6

### ISSUE THREAD

**Issue by nfdevil** [kutlugsahin/ngx-smooth-dnd#6]
Can you update the dependencies to the new release of Angular, so we stop getting warnings like:

`
    warning " > ngx-smooth-dnd@0.1.7" has incorrect peer dependency "@angular/common@^5.1.0". 
    warning " > ngx-smooth-dnd@0.1.7" has incorrect peer dependency "@angular/core@^5.1.0".
`

**Comment by kutlugsahin** [comment]
should be fixed in 0.1.9
